# Generated by Django 2.2 on 2019-04-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessplayer',
            name='first_name',
            field=models.TextField(default='John', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chessplayer',
            name='second_name',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
