# Generated by Django 2.2 on 2019-04-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_auto_20190412_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessplayer',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChessMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('result', models.TextField(choices=[('WHITE_WIN', 'WHITE_WIN'), ('BLACK_WIN', 'BLACK_WIN'), ('DRAW', 'DRAW')], null=True)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_black', to='chess.ChessPlayer')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_white', to='chess.ChessPlayer')),
            ],
        ),
    ]
