# Generated by Django 2.2 on 2019-04-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_auto_20190412_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessmatch',
            name='age_category',
            field=models.TextField(choices=[('UNDER_20', 'UNDER_20'), ('UNDER_30', 'UNDER_30'), ('UNDER_40', 'UNDER_40'), ('UNDER_50', 'UNDER_50'), ('OPEN', 'OPEN')], default='OPEN'),
        ),
    ]
